# Install the conda environment with the following command:
# conda env create --name <my-env-name> --file <path/to/environment.yml>
name: "522-group-28"

channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel=7.1.0
  - nb_conda_kernels=2.5.1
  - pip=25.3
  - quarto=1.8.26
  - pip:
      - graphviz==0.20.1
      - altair_ally==0.1.1
      - pandas==2.3.3
      - scikit-learn==1.7.2
      - requests==2.32.5
      - jinja2==3.1.6
      - altair==6.0.0
      - pandera==0.27.0
      

