# Install the conda environment with the following command:
# conda env create --name <my-env-name> --file <path/to/environment.yml>
name: "522-group-28"

channels:
  - conda-forge
dependencies:
  - python==3.11
  - ipykernel
  - nb_conda_kernels
  - vega_datasets # Example data
  - pip
  - pip:
      - graphviz
      - altair_ally
      - pandas
      - scikit-learn
      - requests
      - jinja2
      - altair
      - pandera==0.27.0

